name: huzur_islamda
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: 14.6.3

  cupertino_icons: ^1.0.8

  logging: ^1.2.0

  #indicator
  smooth_page_indicator: ^1.2.1

  #Lottie animations
  lottie: ^3.3.2

  #Firebase
  firebase_core: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: 2.4.15
  freezed: 3.0.6
  json_serializable: ^6.9.5
  go_router_builder: 2.7.3

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/