// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLLsK6sieiuN8Mkgk34Zl4ESjaltgzwsU',
    appId: '1:418329675000:web:8bcd2e2b4dd4c8d454670d',
    messagingSenderId: '418329675000',
    projectId: 'huzur-islamda-f1bf3',
    authDomain: 'huzur-islamda-f1bf3.firebaseapp.com',
    storageBucket: 'huzur-islamda-f1bf3.firebasestorage.app',
    measurementId: 'G-2BT81DGLKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqD8QfMnrJ8Sr-IRJ_fBnzXkz3JC0dYc',
    appId: '1:418329675000:android:4efa0dd8b2b8665154670d',
    messagingSenderId: '418329675000',
    projectId: 'huzur-islamda-f1bf3',
    storageBucket: 'huzur-islamda-f1bf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx3v0URi9j-u6VOWdqYeE1XjN-zNL_0tk',
    appId: '1:418329675000:ios:bd50dbe8cef22b0a54670d',
    messagingSenderId: '418329675000',
    projectId: 'huzur-islamda-f1bf3',
    storageBucket: 'huzur-islamda-f1bf3.firebasestorage.app',
    iosBundleId: 'com.example.huzurIslamda',
  );
}
