class AppStrings {
  AppStrings._();

  static const String appName = 'İbadet Rehberim';
  static const String cancel = 'İptal';
  static const String start = 'Başla';

  // Onboarding — Sade: uygulamanın amacı (1. sayfa), kısa davet (2. sayfa). Tek animasyon ilk sayfada.
  static const String onboardingNext = 'İleri';
  static const String onboardingTitle1 = 'Hoş Geldiniz';
  static const String onboardingText1 =
      'İslamın ışığında daha huzurlu, dengeli bir yaşam sürmene ve ibadet ile günlük rutinini '
      'düzenli tutmana yardımcı olmak için buradayız.';
  static const String onboardingTitle2 = 'Namaz vakitleri';
  static const String onboardingText2 =
      'Günlük namaz vakitlerini görüntüle, hatırlatmalarla vakitleri kaçırma. Konumuna göre vakitler hesaplanır.';
  static const String onboardingTitle4 = 'Başlamaya hazır mısın?';
  static const String onboardingText4 = 'Beraber bu yolculukta ilerleyelim!';
  static const String onboardingTitle3 = 'Akıllı Zikirmatik';
  static const String onboardingText3 =
      'Günlük zikirlerini oluştur, say ve takip et. Geçmiş zikirlerini görüntüle; ruh haline göre zikir seti oluşturabilirsin.';

  // Settings - Legal texts

  static const String settingsAboutAppDescription =
      'İbadet Rehberim uygulaması, modern hayatın yoğunluğu içinde Kur’an ve sünnet ışığında daha huzurlu, '
      'bilinçli ve dengeli bir yaşam sürmene yardımcı olmak için tasarlanmış bir uygulamadır.\n\n'
      'Uygulama; zikir takipleri, hatırlatmalar, namaz vakitleri, akış içerikleri ve kişisel '
      'manevi hedeflerini destekleyici araçlarla, ibadetlerini ve günlük rutinini düzenli ve '
      'sürdürülebilir hale getirmeyi hedefler.\n\n'
      'Sunulan içeriklerin hiçbiri bir fetva veya bağlayıcı dini hüküm niteliği taşımamakta olup, '
      'genel bilgilendirme ve kişisel gelişim amacıyla hazırlanmıştır. Dini konularda nihai karar ve '
      'sorumluluk kullanıcıya aittir.';

  static const String settingsPrivacyPolicy =
      'Gizlilik Politikası\n'
      'Son Güncelleme Tarihi: 16 Şubat 2026\n\n'
      'İbadet Rehberim olarak, kullanıcılarımızın gizliliğine ve kişisel verilerinin güvenliğine '
      'büyük önem veriyoruz. Bu Gizlilik Politikası, mobil uygulamamızı kullandığınızda verilerinizin nasıl '
      'toplandığını, kullanıldığını, paylaşıldığını ve korunduğunu açıklamaktadır.\n\n'
      'Hizmetlerimizi kullanarak, bu politikada belirtilen uygulamaları kabul etmiş olursunuz.\n\n'
      '1. Toplanan Veriler\n'
      'Uygulamayı daha verimli kullanabilmeniz ve size kişiselleştirilmiş bir deneyim sunabilmek için '
      'aşağıdaki veri türlerini toplamaktayız:\n\n'
      'Kimlik ve İletişim Bilgileri:\n'
      '- Hesap oluşturduğunuzda Ad, Soyad, E-posta adresi ve (isteğe bağlı olarak) doğum tarihi ve cinsiyet '
      'bilgilerinizi toplarız.\n'
      '- Google veya Apple ile giriş yapmanız durumunda, ilgili platform tarafından sağlanan temel profil '
      'bilgilerinizi (ad, e-posta, profil fotoğrafı) işleriz.\n\n'
      'Konum Bilgileri:\n'
      '- Namaz vakitlerini doğru hesaplayabilmek için İlçe, Şehir ve Ülke bazlı konum verilerinizi toplarız.\n'
      '- Bu veriler anlık GPS takibi şeklinde değil, seçtiğiniz veya onayladığınız lokasyon bilgisi olarak '
      'işlenir.\n\n'
      'Kullanım ve İçerik Verileri:\n'
      '- Oluşturduğunuz günlük zikirler, zikir sayılarınız ve "Ruh Haline Göre" oluşturulan zikir setleri.\n'
      '- "Akış" (Flow) bölümünde kaydettiğiniz gönderiler (Saved Posts).\n'
      '- Asistan ile yaptığınız sohbet geçmişi (bağlamı korumak adına son mesajlaşmalar).\n\n'
      'Cihaz ve Teknik Veriler:\n'
      '- IP adresi, cihaz modeli, işletim sistemi sürümü, uygulama çökme raporları (Logs) ve performans '
      'verileri.\n\n'
      'Reklam Verileri:\n'
      '- Ücretsiz sürümü kullanıyorsanız, Google AdMob aracılığıyla reklam gösterimi için cihaz reklam kimliği '
      '(IDFA/GAID) gibi tanımlayıcılar toplanabilir.\n\n'
      '2. Verilerin Kullanım Amaçları\n'
      'Topladığımız verileri şu amaçlarla kullanıyoruz:\n\n'
      '- Hizmetin Sunulması: Namaz vakitlerini konumunuza göre hesaplamak, zikirlerinizi takip etmek ve '
      'kaydetmek.\n'
      '- Hesap Yönetimi: Kimliğinizi doğrulamak, şifre sıfırlama işlemlerini yürütmek ve profilinizi '
      'yönetmenizi sağlamak.\n'
      '- Kişiselleştirme: "Asistan" özelliğinin sorularınıza size özel (örneğin isminizle hitap ederek) yanıt '
      'vermesini sağlamak ve ana akışta ilgi alanlarınıza uygun içerikler sunmak.\n'
      '- İletişim ve Bildirimler: Namaz vakti hatırlatmaları ve günlük zikir hatırlatmalarını (örneğin saat '
      '22:00 gibi) size iletmek.\n'
      '- Geliştirme ve Güvenlik: Uygulamanın hatalarını tespit etmek, güvenliği sağlamak ve kullanıcı '
      'deneyimini iyileştirmek.\n'
      '- Reklam Gösterimi: Premium üye değilseniz, size uygun reklamları sunabilmek (AdMob aracılığıyla).\n\n'
      '3. Verilerin Paylaşımı\n'
      'Kişisel verilerinizi, yasal zorunluluklar veya hizmetin işleyişi haricinde üçüncü şahıslara satmayız. '
      'Verileriniz yalnızca aşağıdaki durumlarda paylaşılabilir:\n\n'
      '- Hizmet Sağlayıcılar: Uygulamanın altyapısını sağlayan güvenilir üçüncü taraf hizmetler (örneğin '
      'veritabanı ve kimlik doğrulama için Google Firebase, reklam gösterimi için Google AdMob).\n'
      '- Yasal Zorunluluklar: Kanunen yetkili kamu kurum ve kuruluşlarından gelen yasal talepler doğrultusunda '
      'verileriniz paylaşılabilir.\n'
      '- Ödeme İşlemleri: Premium abonelik (Haftalık/Yıllık) satın alımlarınız Apple App Store veya Google Play '
      'Store ödeme sistemleri üzerinden gerçekleşir. Kredi kartı bilgileriniz sunucularımızda tutulmaz.\n\n'
      '4. Veri Güvenliği\n'
      'Verilerinizin güvenliği bizim için önceliklidir:\n\n'
      '- Verileriniz Firebase (Google Cloud) güvencesindeki sunucularda saklanmaktadır.\n'
      '- Uygulama ile sunucular arasındaki veri iletişimi SSL/TLS şifreleme teknolojisi ile korunmaktadır.\n'
      '- Zikir verileriniz gibi bazı tercihleriniz cihazınızda yerel olarak (Hive veritabanı) şifreli veya '
      'şifresiz şekilde, cihaz güvenliğinize bağlı olarak saklanır.\n'
      '- Hesabınıza erişim şifre korumalıdır. Şifrenizin güvenliğinden siz sorumlusunuz.\n\n'
      '5. Haklarınız\n'
      'Kullanıcı olarak kişisel verileriniz üzerinde aşağıdaki haklara sahipsiniz:\n\n'
      '- Erişim ve Düzeltme: Profil sayfanızdan kişisel bilgilerinizi (ad, soyad, konum vb.) dilediğiniz zaman '
      'görüntüleyebilir ve güncelleyebilirsiniz.\n'
      '- Veri Silme (Unutulma Hakkı): Uygulama içerisindeki Ayarlar > Hesap > Hesabı Sil seçeneğini kullanarak '
      'hesabınızı ve ilişkili tüm verilerinizi kalıcı olarak silebilirsiniz. Ayrıca web sitemizdeki talep '
      'formunu kullanarak da silme talebinde bulunabilirsiniz.\n'
      '- İtiraz ve Kısıtlama: Verilerinizin işlenmesine itiraz etme hakkınız saklıdır.\n'
      '- Bildirimleri Kapatma: Ayarlar menüsünden namaz ve zikir bildirimlerini dilediğiniz zaman '
      'kapatabilirsiniz.\n\n'
      'Uygulamayı kullanmaya devam ederek, bu gizlilik politikasını okuduğunuzu ve kabul ettiğinizi beyan '
      'etmiş olursunuz.';

  static const String settingsTermsOfService =
      'Kullanım Koşulları\n'
      'Son Güncelleme Tarihi: 16 Şubat 2026\n\n'
      '1. Genel Hükümler\n'
      'İbadet Rehberim uygulamasına ("Uygulama") hoş geldiniz. Bu uygulamayı indirerek veya kullanarak, bu '
      'kullanım koşullarını peşinen kabul etmiş sayılırsınız.\n\n'
      'Hizmetin Tanımı: Uygulama; kullanıcılara namaz vakitleri takibi, zikirmatik, İslami içerik akışı ve '
      'yapay zeka destekli asistan hizmeti sunan bir mobil platformdur.\n\n'
      'Dini İçerik Uyarısı: Uygulama içerisinde sunulan namaz vakitleri, kıble yönü, hadisler ve yapay zeka '
      'asistanı tarafından verilen yanıtlar yalnızca bilgilendirme ve yardımcı olma amaçlıdır. Bu bilgiler '
      'kesin dini hüküm (fetva) niteliği taşımaz. Dini vecibelerinizi yerine getirirken nihai doğrulama '
      'sorumluluğu kullanıcıya aittir.\n\n'
      'Abonelikler: Uygulama, reklamsız kullanım gibi özellikler için ücretli abonelik paketleri '
      '(Haftalık/Yıllık) sunabilir. Ödemeler Apple App Store veya Google Play Store hesabınız üzerinden '
      'gerçekleştirilir ve ilgili mağazanın iptal/iade koşullarına tabidir.\n\n'
      '2. Kullanıcı Yükümlülükleri\n'
      'Uygulamayı kullanırken aşağıdaki hususlara uymayı taahhüt edersiniz:\n\n'
      'Hesap Güvenliği: Hesap oluştururken verdiğiniz bilgilerin (E-posta, Ad, Soyad vb.) doğru olduğunu beyan '
      'eder; şifrenizin güvenliğinden bizzat sorumlu olduğunuzu kabul edersiniz.\n\n'
      'Uygun Kullanım: "Akış" (Flow) veya "Asistan" bölümlerinde yapacağınız etkileşimlerde, genel ahlaka, '
      'İslam adabına ve yasalara aykırı, hakaret içeren veya yanıltıcı içerik üretmemeyi/paylaşmamayı taahhüt '
      'edersiniz.\n\n'
      'Kötüye Kullanım: Uygulamanın teknik yapısına zarar verecek, tersine mühendislik (reverse engineering) '
      'içeren veya sistemin açığını arayan faaliyetlerde bulunamazsınız.\n\n'
      '3. Fikri Mülkiyet\n'
      'Uygulama Hakları: İbadet Rehberim uygulamasının yazılımı, tasarımı, logosu, veritabanı yapısı ve '
      'oluşturulan özgün içeriklerin tüm mülkiyet hakları geliştiriciye aittir.\n\n'
      'Dini Metinler: Uygulamada yer alan Kur\'an-ı Kerim ayetleri ve Hadis metinleri evrensel olup telif '
      'hakkına tabi değildir; ancak bu metinlerin derleniş biçimi, sunumu ve çeviri veritabanları uygulamanın '
      'fikri mülkiyetindedir.\n\n'
      'Kullanım Lisansı: Size, uygulamayı yalnızca kişisel ve ticari olmayan amaçlarla kullanmanız için '
      'sınırlı, devredilemez bir lisans verilir. Uygulamanın bir kısmını veya tamamını kopyalamak, satmak '
      'veya izinsiz dağıtmak yasaktır.\n\n'
      '4. Hizmetin Değiştirilmesi veya Sona Ermesi\n'
      'Güncellemeler: Geliştirici, uygulamanın özelliklerini (örneğin Asistanın yeteneklerini veya zikir '
      'özelliklerini) dilediği zaman güncelleme, değiştirme veya kaldırma hakkını saklı tutar.\n\n'
      'Fesih Hakkı: Kullanım koşullarına aykırı hareket eden kullanıcıların hesapları (özellikle uygunsuz '
      'içerik bildirimi veya raporlama durumlarında) haber verilmeksizin askıya alınabilir veya '
      'silinebilir.\n\n'
      'Hizmetin Durdurulması: Geliştirici, teknik veya ticari sebeplerle uygulamanın yayınına geçici veya '
      'kalıcı olarak son verebilir.\n\n'
      '5. Sorumluluk Sınırı\n'
      'Teknik Hatalar: Namaz vakitleri hesaplamaları coğrafi konuma ve seçilen hesaplama yöntemine göre '
      'değişiklik gösterebilir. Uygulama, olası yazılımsal hatalardan, GPS sapmalarından veya vakit '
      'uyumsuzluklarından doğabilecek manevi sorumlulukları kabul etmez. Temkin sürelerini kontrol etmek '
      'kullanıcının sorumluluğundadır.\n\n'
      'Yapay Zeka (Asistan): Uygulama içindeki asistan, yapay zeka teknolojisi ile çalışmaktadır. Verdiği '
      'yanıtların %100 doğruluğu garanti edilmez. Asistanın dini konulardaki yorumları referans alınarak ibadet '
      'değişikliğine gidilmemelidir.\n\n'
      'Üçüncü Taraf Reklamlar: Uygulamanın ücretsiz sürümünde (AdMob aracılığıyla) gösterilen reklamların '
      'içeriği reklam verenin sorumluluğundadır; geliştirici bu içeriklerden sorumlu tutulamaz.\n\n'
      'Veri Kaybı: Cihazınızda veya sunucularda (Firebase/Hive) oluşabilecek teknik arızalar sonucu zikir '
      'sayacı veya kaydedilen gönderilerin kaybolmasından uygulama sorumlu değildir.\n\n'
      '6. Uygulanacak Hukuk ve İletişim\n'
      'Hukuk: İşbu Kullanım Koşulları\'ndan doğacak her türlü uyuşmazlıkta Türkiye Cumhuriyeti Kanunları '
      'uygulanacaktır.\n\n'
      'Yetkili Mahkeme: Uyuşmazlıkların çözümünde İstanbul (Merkez) Mahkemeleri ve İcra Daireleri yetkilidir.\n\n'
      'İletişim: Uygulama ile ilgili her türlü soru, öneri, telif hakkı bildirimi veya hesap silme talepleriniz '
      'için bizimle aşağıdaki kanaldan iletişime geçebilirsiniz:\n\n'
      'E-posta: destek@ibadetrehberim.com\n'
      'Web Sitesi: www.ibadetrehberim.com';
}
